### ISSUE TITLE
Inference Script causes a mishape error.

### ISSUE THREAD

**Issue by miqu-s** [uthree/tinyvc#3]
```
Traceback (most recent call last):
  File "/content/infer.py", line 79, in <module>
    out, buffer = convertor.convert(chunk, buffer, tgt, args.pitch_shift, device, args.f0_estimation)
  File "/content/module/convertor.py", line 79, in convert
    z = match_features(z, tgt)
  File "/content/module/decoder.py", line 72, in match_features
    sims = torch.bmm(source / source_norm, (reference / reference_norm).transpose(1, 2))
RuntimeError: Expected size for first two dimensions of batch2 tensor to be: [1, 768] but got: [2, 768].
```

**Comment by miqu-s** [comment]
Reshaping causes a fix. Will be making a PR.
